### ISSUE TITLE
Create generic exception tester

### ISSUE THREAD

**Issue by WJSchakel** [averbraeck/djutils-base#10]
Include generic code as mentioned in https://github.com/averbraeck/opentrafficsim/issues/157.

**Comment by averbraeck** [comment]
In order to make this work, the exception tester should be part of the production code of djutils-base, and not part of the test code, since it cannot be called from the jar file if it is test code. A package `org.djutils.test` can be added to store generic test code that many projects can use.

**Comment by averbraeck** [comment]
The generic class `ExceptionTest` with a static method `testExceptionClass(clazz)` has been created. Unit tests have also been made. The API of junit had to be made available in the regular code base, rather than just in the test code base. The junit engine remains just in the test code base, however.
